ci: run based on main

diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -7,11 +7,28 @@ on:
 
 jobs:
   build-image:
-    name: Build Docker Image
+    name: Build Docker image
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2.5.0
 
-      - name: Build Image
+      - name: Build image
         run: docker build -t myimage:latest .
+
+  units-tests:
+    name: Unit tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+      uses: actions/checkout@v2.5.0
+
+      - name: Run tests
+      run: |
+        if [[ "$NAME" = "sean" ]]; then
+          echo "pass"
+          exit 0
+        else
+          echo "fail"
+          exit 1
+        fi
